{% set name = "skinnywms" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 326e117190ff0d7bec9a9e0c83092faa7ef26b0b7d2590ff58cb97bf2450a5b6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - skinny-wms=skinnywms.skinny:main

requirements:  
  host:
    - python >3.5
    - pip
    - magics
  run:
    - python >3.5
    - flask
    - magics
    - xarray >=0.12.0

test:
  imports:
    - skinnywms
  

about:
  home: http://github.com/ecmwf/skinnywms
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Simple WMSserver to visualise NetCDF and GRIB data'
  description: 'Visualising meteorological and climate data'
  doc_url: http://github.com/ecmwf/skinnywms
  dev_url: https://github.com/ecmwf/skinnywms

extra:
  recipe-maintainers:
    - sylvielamythepaut
    - milanavuckovic
