travis:
  secure:
    BINSTAR_TOKEN: rQo3/Bzvt36ilF+SG8t7xFP7CrypYYoGaKpOAp38O3jHv/hvNzi/J+szdpkSIli82FUlx2398LHjllWk0/oUK1MH2Ixk++J9yXoH0Ff5r4fA5fJBeD3bCdjqWopEfiEa+6Jtf7RfU5/rg9/8XTVix9BG0NJfm72QTPnLek05bNuGCj+Mhne+XOT1TUA4ikEiHf5YUmLwrvl2Nl1Slg2WjeC8Q/mSuOIDrsZghnfEhE2q/2DV/m2pqoZeI0lDcbZOL1nmqbxBPwMbnyfpggEA9LKUMty54pkW8OuKeAml4KKosoFi2uxEonhvwOzKPdr25dPSR2VkS4de5pjvzFuXr6vGhuNFOWe8Zd33q41DEqDSoZm8hbrgz0wgbV5MM7jgnIlMAmISYjcbBwR+9C8RfI9I2O7rts0ssOJN/RC2c6D4Veaf0o+p3YYkQ15HnBssHJ30JTPCd+g9CT3iofMC/kGo54L0asqhTcq07Ka8lo9fZx1+Co/9TvuVnF7ZOk58mZyISd2G28e0cDbdNYfBSTsO8tXDIuw8JdcYLNL5z+W8luoebZyBKUkVqhGZ8z/LYE5pGdsbgNOyrl+aRUx+FVKF4yYBX6vG/txh3bqMPKMY3TXc4xCmhRg4d6nke/B9KXX2WXLpIltQkgY/05YcEERFcG+0yT6RoGuXefKfcdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
